'use strict';

function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}

const CATS = [
  {id:'cbc',      label:'CBC'},
  {id:'bmp',      label:'BMP / Electrolytes'},
  {id:'lft',      label:'Liver / Proteins'},
  {id:'coag',     label:'Coagulation'},
  {id:'cardiac',  label:'Cardiac'},
  {id:'thyroid',  label:'Thyroid'},
  {id:'endocrine',label:'Endocrine'},
  {id:'lipids',   label:'Lipids'},
  {id:'ua',       label:'Urinalysis'},
  {id:'abg',      label:'ABG'},
  {id:'misc',     label:'Miscellaneous'},
  {id:'immune',   label:'Immunology'},
  {id:'tumor',    label:'Tumor Markers'},
  {id:'drug',     label:'Drug Levels'},
];

// Each entry: {cat, name, male, female (omit if same), units, note, aliases (for search)}
const LABS = [

  // CBC
  {cat:'cbc', name:'WBC', male:'4.5–11.0', units:'×10³/µL', note:'Differential required for full interpretation. Leukocytosis >11k or leukopenia <4k warrants evaluation.', aliases:'white blood cell count leukocyte'},
  {cat:'cbc', name:'RBC', male:'4.5–5.9', female:'4.0–5.2', units:'×10⁶/µL', note:'Red blood cell count; use with Hgb/Hct for anemia evaluation.', aliases:'red blood cell erythrocyte'},
  {cat:'cbc', name:'Hemoglobin', male:'13.5–17.5', female:'12.0–16.0', units:'g/dL', note:'Anemia: male <13.5, female <12.0 g/dL (WHO). Transfusion typically considered <7 g/dL in stable patients.', aliases:'hgb hb haemoglobin'},
  {cat:'cbc', name:'Hematocrit', male:'41–53', female:'36–48', units:'%', note:'Hct ≈ Hgb × 3. Polycythemia vera: >52% (M), >48% (F).', aliases:'hct packed cell volume pcv'},
  {cat:'cbc', name:'MCV', male:'80–100', units:'fL', note:'Microcytic <80: iron def, thalassemia, sideroblastic. Macrocytic >100: B12/folate, alcohol, hypothyroid, medications.', aliases:'mean corpuscular volume'},
  {cat:'cbc', name:'MCH', male:'27–33', units:'pg', note:'Mean corpuscular hemoglobin; parallels MCV.', aliases:'mean corpuscular hemoglobin'},
  {cat:'cbc', name:'MCHC', male:'32–36', units:'g/dL', note:'Mean corpuscular hemoglobin concentration. MCHC >36 = spherocytosis; <32 = hypochromic anemia.', aliases:'mean corpuscular hemoglobin concentration'},
  {cat:'cbc', name:'RDW', male:'11.5–14.5', units:'%', note:'Elevated in iron deficiency, B12/folate deficiency, mixed anemia, recent transfusion.', aliases:'red cell distribution width'},
  {cat:'cbc', name:'Platelets', male:'150–400', units:'×10³/µL', note:'Thrombocytopenia <150k: investigate. Critical <50k (bleeding risk); <10k (spontaneous hemorrhage risk). Thrombocytosis >400k.', aliases:'plt thrombocytes'},
  {cat:'cbc', name:'MPV', male:'7.5–12.5', units:'fL', note:'Mean platelet volume. Elevated MPV with thrombocytopenia may suggest ITP or peripheral destruction.', aliases:'mean platelet volume'},
  {cat:'cbc', name:'Neutrophils', male:'1.8–7.5 (40–70%)', units:'×10³/µL (%)', note:'ANC <500 = severe neutropenia (infection risk). ANC <100 = profound neutropenia. Bands >10% may suggest left shift.', aliases:'anc abs neutrophil count pmn segmented'},
  {cat:'cbc', name:'Lymphocytes', male:'1.0–4.8 (20–40%)', units:'×10³/µL (%)', note:'Lymphopenia <1.0k: HIV, immunosuppressants, severe illness. Lymphocytosis in viral infections, CLL.', aliases:'lymphs'},
  {cat:'cbc', name:'Monocytes', male:'0.2–1.0 (2–10%)', units:'×10³/µL (%)', note:'Elevated in chronic infection, inflammatory disease, monocytic leukemia.', aliases:'monos'},
  {cat:'cbc', name:'Eosinophils', male:'0–0.45 (0–4%)', units:'×10³/µL (%)', note:'Eosinophilia >0.5k: parasites, allergy, drug reaction, eosinophilic disorders. >1.5k = hypereosinophilia syndrome.', aliases:'eos'},
  {cat:'cbc', name:'Basophils', male:'0–0.1 (0–1%)', units:'×10³/µL (%)', note:'Basophilia seen in CML, allergic states, hypothyroidism.', aliases:'basos'},
  {cat:'cbc', name:'Reticulocytes (%)', male:'0.5–2.5', units:'%', note:'Elevated = active erythropoiesis (hemolysis, bleeding, treatment response). Low = hypoproliferative anemia (iron deficiency, B12/folate, aplastic anemia, CKD). Use with absolute count for complete picture. Reticulocyte production index (RPI) = (retic% × Hct/45) / maturation factor; RPI <2 with anemia = inadequate marrow response.', aliases:'reticulocyte count retic retics reticulocytes percentage'},
  {cat:'cbc', name:'Reticulocytes (absolute)', male:'25–100', units:'×10³/µL', note:'More clinically useful than percentage alone. >100k = hyperproliferative (hemolysis, recovery). <25k with anemia = hypoproliferative. Rises within 3–5 days of iron or B12/folate replacement — earliest sign of treatment response.', aliases:'absolute reticulocyte count arc reticulocytes'},
  {cat:'cbc', name:'Immature Reticulocyte Fraction', male:'<0.15', units:'fraction', note:'IRF reflects bone marrow erythropoietic activity. First parameter to rise after iron/B12/EPO therapy (within 2–3 days) and after stem cell transplant engraftment. Elevated in active hemolysis and marrow recovery. Useful for monitoring engraftment timing post-transplant.', aliases:'irf immature reticulocyte fraction rmi reticulocyte maturity'},

  // BMP / Electrolytes
  {cat:'bmp', name:'Sodium', male:'136–145', units:'mEq/L', note:'Hyponatremia <136: SIADH, hypothyroid, adrenal insufficiency, hypervolemic states. Hypernatremia >145: dehydration, DI. Correct for glucose if hyperglycemic: +1.6 mEq/L per 100 mg/dL glucose >100.', aliases:'na serum sodium'},
  {cat:'bmp', name:'Potassium', male:'3.5–5.1', units:'mEq/L', note:'Hemolysis falsely elevates. Hypokalemia <3.5: replace; EKG changes <3.0. Hyperkalemia >5.5: evaluate for pseudohyperkalemia, CKD, medications.', aliases:'k serum potassium'},
  {cat:'bmp', name:'Chloride', male:'98–107', units:'mEq/L', note:'Elevated in metabolic acidosis with normal AG. Low in metabolic alkalosis, SIADH.', aliases:'cl serum chloride'},
  {cat:'bmp', name:'CO₂ (Bicarbonate)', male:'22–29', units:'mEq/L', note:'Venous CO2 approximates arterial HCO3 + 2 mEq/L. Low = metabolic acidosis or respiratory compensation. High = metabolic alkalosis or respiratory acidosis.', aliases:'bicarbonate hco3 co2 bicarb'},
  {cat:'bmp', name:'BUN', male:'7–25', units:'mg/dL', note:'BUN:Cr ratio >20:1 suggests prerenal azotemia. Elevated in GI bleeding, high protein, dehydration, catabolic states.', aliases:'blood urea nitrogen urea'},
  {cat:'bmp', name:'Creatinine', male:'0.7–1.2', female:'0.5–1.0', units:'mg/dL', note:'Sex- and muscle mass-dependent. Not reliable for drug dosing alone — use eGFR (CKD staging) or CrCl (drug dosing). Inaccurate in AKI (not at steady state).', aliases:'cr creatinine serum'},
  {cat:'bmp', name:'eGFR (CKD-EPI 2021)', male:'≥60', units:'mL/min/1.73m²', note:'CKD staging: G1 ≥90 (normal/high), G2 60–89 (mildly decreased), G3a 45–59, G3b 30–44, G4 15–29, G5 <15. Race-free CKD-EPI 2021 equation now standard. Use with albuminuria (UACR) for complete CKD staging. Not reliable in AKI, extremes of muscle mass, pregnancy.', aliases:'egfr gfr ckd kidney function glomerular filtration'},
  {cat:'bmp', name:'Glucose (fasting)', male:'70–99', units:'mg/dL', note:'Prediabetes: 100–125 mg/dL. Diabetes: ≥126 mg/dL on 2 occasions or symptoms + random ≥200. Critical hypoglycemia <40 mg/dL.', aliases:'glucose blood sugar fbs'},
  {cat:'bmp', name:'Calcium (total)', male:'8.5–10.2', units:'mg/dL', note:'Correct for albumin: corrected Ca = measured Ca + 0.8 × (4.0 − albumin). Ionized calcium is more accurate in critically ill. Symptoms: tetany (<7.5), cardiac arrhythmia (>12).', aliases:'ca calcium serum total'},
  {cat:'bmp', name:'Magnesium', male:'1.7–2.2', units:'mg/dL', note:'Hypomagnesemia causes refractory hypokalemia and hypoparathyroidism. Replace if <1.8 in cardiac patients. 1 mg/dL = 0.41 mmol/L.', aliases:'mg serum magnesium'},
  {cat:'bmp', name:'Phosphorus', male:'2.5–4.5', units:'mg/dL', note:'Hypophosphatemia: refeeding syndrome, hyperparathyroidism, DKA treatment. Hyperphosphatemia: CKD, hypoparathyroidism.', aliases:'phos phosphate serum'},
  {cat:'bmp', name:'Serum Osmolality', male:'275–295', units:'mOsm/kg', note:'Calculated: 2×Na + glucose/18 + BUN/2.8. Measured by freezing point depression. Osmol gap = measured − calculated; >10 mOsm/kg suggests unmeasured osmoles (toxic alcohols, mannitol, propylene glycol). Hyperosmolality >320 mOsm/kg: severe dehydration, hyperosmolar hyperglycemic state (HHS).', aliases:'serum osmolality osmolarity tonicity measured'},
  {cat:'bmp', name:'Osmol Gap', male:'<10', units:'mOsm/kg', note:'Osmol gap = measured osmolality − [2×Na + glucose/18 + BUN/2.8]. >10 mOsm/kg suggests unmeasured osmoles. Causes: ethanol (~22 mOsm/kg per 100 mg/dL), methanol, ethylene glycol, isopropanol, mannitol. Helpful in suspected toxic alcohol ingestion even before confirmation by specific levels.', aliases:'osmol gap osmolar gap toxic alcohol methanol ethylene glycol'},
  {cat:'bmp', name:'Anion Gap', male:'8–12', units:'mEq/L', note:'AG = Na − (Cl + HCO3). Normal 8–12 mEq/L; correct for albumin: add 2.5 mEq/L per 1 g/dL below 4.0. MUDPILES: methanol, uremia, DKA/alcoholic KA, propylene glycol, INH/iron, lactic acidosis, ethylene glycol, salicylates. Delta-delta ratio (ΔAG/ΔHCO3) evaluates for mixed disorders.', aliases:'anion gap ag metabolic acidosis mudpiles delta gap'},

  // LFTs / Proteins
  {cat:'lft', name:'Total Protein', male:'6.0–8.3', units:'g/dL', note:'Low in malnutrition, liver failure, protein-losing states. High in dehydration, multiple myeloma, sarcoidosis.', aliases:'tp total protein serum'},
  {cat:'lft', name:'Albumin', male:'3.5–5.0', units:'g/dL', note:'Half-life ~20 days — marker of chronic nutritional status, not acute change. Low in chronic inflammation, malabsorption, nephrotic syndrome, liver cirrhosis.', aliases:'alb serum albumin'},
  {cat:'lft', name:'Prealbumin (Transthyretin)', male:'15–40', units:'mg/dL', note:'Half-life 2–3 days (vs albumin ~20 days) — superior marker for acute nutritional change or recovery. Low in malnutrition, liver failure, acute inflammation (negative acute-phase reactant), post-op catabolism. More sensitive than albumin for short-term monitoring of nutritional status and response to therapy.', aliases:'prealbumin transthyretin ttr nutrition acute'},
  {cat:'lft', name:'Total Bilirubin', male:'0.3–1.2', units:'mg/dL', note:'>2.5 mg/dL = clinical jaundice. Elevated in hemolysis, hepatocellular disease, or cholestasis. Fractionation distinguishes conjugated vs unconjugated.', aliases:'tbili tbilirubin bilirubin total'},
  {cat:'lft', name:'Direct Bilirubin', male:'0.0–0.3', units:'mg/dL', note:'Direct >50% of total = conjugated hyperbilirubinemia (hepatocellular or cholestatic cause). Indirect predominance = hemolysis or Gilbert syndrome.', aliases:'direct bili conjugated bilirubin'},
  {cat:'lft', name:'Indirect Bilirubin', male:'0.2–1.0', units:'mg/dL', note:'Indirect = Total − Direct. Elevated in hemolysis, Gilbert syndrome, neonatal jaundice.', aliases:'indirect bili unconjugated bilirubin'},
  {cat:'lft', name:'ALT (SGPT)', male:'7–56', female:'7–45', units:'U/L', note:'Most liver-specific aminotransferase. >3× ULN suggests significant hepatocellular injury. AST:ALT ratio >2:1 suggests alcoholic hepatitis.', aliases:'sgpt alanine aminotransferase alanine transaminase'},
  {cat:'lft', name:'AST (SGOT)', male:'10–40', units:'U/L', note:'Less liver-specific than ALT (also elevated in muscle, heart). AST:ALT >2:1 = alcoholic hepatitis; >3:1 strongly suggests alcoholic. Also elevated in rhabdomyolysis, MI.', aliases:'sgot aspartate aminotransferase aspartate transaminase'},
  {cat:'lft', name:'ALP (Alkaline Phosphatase)', male:'44–147', units:'U/L', note:'Elevated in cholestasis, Paget disease, bone metastases, pregnancy (placental isoenzyme). Confirm hepatic origin with GGT elevation.', aliases:'alk phos alkaline phosphatase'},
  {cat:'lft', name:'GGT (Gamma-GT)', male:'8–61', female:'5–36', units:'U/L', note:'Sensitive for hepatic/biliary disease and alcohol use. Not organ-specific alone; useful as hepatic marker paired with ALP. Elevated by many medications.', aliases:'ggt gamma gt glutamyltransferase'},
  {cat:'lft', name:'LDH', male:'140–280', units:'U/L', note:'Nonspecific; elevated in hemolysis, malignancy, PE, MI, liver disease. Very high in lymphoma, megaloblastic anemia (>1000 U/L). Prognostically important in lymphoma staging (DLBCL IPI) and testicular cancer (NSGCT staging).', aliases:'lactic acid dehydrogenase lactate dehydrogenase ldh'},
  {cat:'lft', name:'Ceruloplasmin', male:'18–36', units:'mg/dL', note:'Copper-carrying protein synthesized in liver. Low in Wilson disease (<20 mg/dL; confirm with 24h urine copper >100 µg/day and slit-lamp Kayser-Fleischer rings). Also low in malnutrition, nephrotic syndrome, malabsorption. Elevated as acute-phase reactant in pregnancy/estrogen use — can paradoxically mask Wilson disease.', aliases:'ceruloplasmin wilson disease copper'},

  // Coagulation
  {cat:'coag', name:'PT (Prothrombin Time)', male:'11–13.5', units:'seconds', note:'Extrinsic/common pathway. Prolonged by warfarin, factor VII/X/V/II/I deficiency, liver disease, vitamin K deficiency.', aliases:'pt protime prothrombin time'},
  {cat:'coag', name:'INR', male:'0.8–1.2', units:'ratio', note:'Therapeutic: AFib 2.0–3.0; mechanical mitral valve 2.5–3.5; mechanical aortic valve 2.0–3.0. Supratherapeutic: consider bleeding risk vs reversal.', aliases:'international normalized ratio'},
  {cat:'coag', name:'aPTT', male:'25–35', units:'seconds', note:'Intrinsic/common pathway. Prolonged by heparin, factor VIII/IX/XI/XII deficiency, lupus anticoagulant (paradoxically increases clot risk). Heparin therapy target: 60–100 sec (1.5–2.5× normal).', aliases:'aptt ptt partial thromboplastin time activated'},
  {cat:'coag', name:'Fibrinogen', male:'200–400', units:'mg/dL', note:'Acute phase reactant (elevated in inflammation). Low in DIC, severe liver failure, fibrinolysis, asparaginase therapy. Critical <100 mg/dL.', aliases:'fibrinogen serum'},
  {cat:'coag', name:'D-dimer', male:'<0.50', units:'µg/mL FEU', note:'Age-adjusted cutoff: age × 10 ng/mL for age >50 (improves specificity). Near 100% sensitivity for VTE if low pre-test probability; specificity only ~50%. Elevated in infection, pregnancy, malignancy, post-op.', aliases:'d dimer fibrin degradation'},
  {cat:'coag', name:'Thrombin Time', male:'14–19', units:'seconds', note:'Prolonged by heparin, fibrinogen deficiency, paraproteins, thrombin inhibitors (argatroban, dabigatran).', aliases:'thrombin time tt'},
  {cat:'coag', name:'Anti-Xa (UFH)', male:'0.3–0.7', units:'IU/mL', note:'Preferred monitoring assay for unfractionated heparin (UFH) in patients with baseline aPTT abnormalities (lupus anticoagulant, factor deficiencies). Therapeutic range for VTE treatment: 0.3–0.7 IU/mL. Draw 6h after infusion rate change at steady state. Increasingly preferred over aPTT for UFH monitoring.', aliases:'anti xa antifactor xa heparin monitoring ufh unfractionated'},
  {cat:'coag', name:'Anti-Xa (LMWH)', male:'0.5–1.0 (BID)', units:'IU/mL', note:'LMWH monitoring not routinely required but indicated in renal failure (CrCl <30), obesity (BMI >40), pregnancy. Draw 4h after SubQ dose. Prophylactic target: 0.2–0.5 IU/mL; therapeutic BID target: 0.5–1.0 IU/mL; once-daily therapeutic target: 1.0–2.0 IU/mL.', aliases:'anti xa antifactor xa lmwh enoxaparin lovenox monitoring'},

  // Cardiac
  {cat:'cardiac', name:'Troponin I (conventional)', male:'<0.04', units:'ng/mL', note:'Use lab-specific reference range — assays vary greatly. Rise begins 3–4h, peaks 24–48h, returns to normal 7–10 days. Serial values critical for diagnosis.', aliases:'troponin tni cardiac marker'},
  {cat:'cardiac', name:'Troponin I (high-sensitivity)', male:'<34', female:'<16', units:'ng/L', note:'Sex-specific cutoffs required. 0h/1h or 0h/2h protocols allow rapid rule-in/rule-out. Use institutional reference values.', aliases:'hs troponin high sensitivity hstni'},
  {cat:'cardiac', name:'Troponin T (high-sensitivity)', male:'<53', female:'<53', units:'ng/L', note:'Combined sex-specific cutoffs for most assays (e.g., Roche Elecsys hs-TnT). Check institutional reference values.', aliases:'hs troponin t hstnt'},
  {cat:'cardiac', name:'BNP', male:'<100', units:'pg/mL', note:'Heart failure unlikely <100 pg/mL; likely >400 pg/mL. Values 100–400: consider other causes (PE, ACS, CKD). BMI and age affect levels.', aliases:'bnp brain natriuretic peptide b-natriuretic'},
  {cat:'cardiac', name:'NT-proBNP', male:'<125 (age <75)\n<900 (age ≥75)', units:'pg/mL', note:'Age-adjusted HF rule-out: <300 pg/mL. Age-adjusted rule-in: 450 (<50yr), 900 (50–75yr), 1800 (>75yr). Values 300–450/900/1800 = gray zone.', aliases:'nt pro bnp ntprobnp'},
  {cat:'cardiac', name:'CK (Creatine Kinase)', male:'22–198', units:'U/L', note:'Elevated in rhabdomyolysis (often >10,000), MI, myositis, hypothyroidism, vigorous exercise, medications (statins). CK-MB and troponin differentiate cardiac.', aliases:'ck cpk creatine kinase creatine phosphokinase'},
  {cat:'cardiac', name:'CK-MB', male:'0–5', units:'ng/mL', note:'More cardiac-specific than total CK. Less sensitive than troponin for MI. Useful for re-infarction detection (shorter half-life than troponin). CK-MB/Total CK ratio >5% suggests cardiac origin.', aliases:'ckmb creatine kinase mb'},
  {cat:'cardiac', name:'Myoglobin', male:'<90', units:'µg/L', note:'Rises within 1–3h of MI — earliest marker but nonspecific (also elevated in muscle injury). Negative value can exclude MI early. Used less frequently now with hs-Tn.', aliases:'myoglobin serum'},
  {cat:'cardiac', name:'Homocysteine', male:'<15', units:'µmol/L', note:'Elevated (>15 µmol/L) is an independent ASCVD risk enhancer. Most common cause: B12, folate, or B6 deficiency. Also elevated in renal failure, hypothyroidism, MTHFR polymorphism, medications (MTX, phenytoin, nicotinic acid). Treat with B vitamins if deficiency confirmed.', aliases:'homocysteine serum cardiovascular risk hcy'},

  // Thyroid
  {cat:'thyroid', name:'TSH', male:'0.45–4.5', units:'µIU/mL', note:'Best initial test. Suppressed TSH + high T4 = hyperthyroidism. Elevated TSH + low T4 = hypothyroidism. TSH alone sufficient for monitoring stable hypothyroid on levothyroxine.', aliases:'thyroid stimulating hormone thyrotropin tsh'},
  {cat:'thyroid', name:'Free T4', male:'0.8–1.8', units:'ng/dL', note:'Order when TSH is abnormal. Primary test for hypothyroidism after TSH. Low fT4 with high TSH = primary hypothyroidism. Low fT4 with low/normal TSH = central hypothyroidism.', aliases:'ft4 free thyroxine t4 free'},
  {cat:'thyroid', name:'Free T3', male:'2.3–4.2', units:'pg/mL', note:'T3 thyrotoxicosis: high T3 with normal T4. Not routinely ordered; useful when hyperthyroidism suspected with normal fT4. Lower in sick euthyroid syndrome.', aliases:'ft3 free triiodothyronine t3 free'},
  {cat:'thyroid', name:'Total T4', male:'5.0–12.0', units:'µg/dL', note:'Affected by TBG levels (pregnancy, estrogen use elevate TBG → high total T4 with normal free T4). Less useful than free T4 in most settings.', aliases:'total thyroxine t4 total'},
  {cat:'thyroid', name:'Total T3', male:'80–200', units:'ng/dL', note:'Mainly protein-bound. Less affected by protein changes than total T4. T3 toxicosis: high T3 with normal T4.', aliases:'total triiodothyronine t3 total'},
  {cat:'thyroid', name:'Reverse T3', male:'10–24', units:'ng/dL', note:'Inactive T3 metabolite; produced preferentially in critical illness, fasting, and physiologic stress (sick euthyroid syndrome). Elevated rT3 with low T3 in hospitalized patients is normal physiology — not thyroid disease. Avoid ordering in acutely ill patients; rarely changes management.', aliases:'rt3 reverse t3 reverse triiodothyronine sick euthyroid'},
  {cat:'thyroid', name:'Anti-TPO', male:'<35', units:'IU/mL', note:'Elevated in Hashimoto thyroiditis (>90%), Graves disease, ~10% of healthy adults. Marker of autoimmune thyroid disease.', aliases:'anti tpo thyroid peroxidase antibody tpo ab'},
  {cat:'thyroid', name:'Anti-Thyroglobulin Ab', male:'<20', units:'IU/mL', note:'Elevated in Hashimoto, Graves. Can interfere with thyroglobulin assay used for thyroid cancer monitoring.', aliases:'anti thyroglobulin ab tg ab'},
  {cat:'thyroid', name:'TSI (Thyroid Stimulating Ig)', male:'<140%', units:'% baseline', note:'Highly specific for Graves disease. Used to confirm diagnosis and guide treatment duration. Elevated in active disease, decreases with treatment.', aliases:'tsi thyroid stimulating immunoglobulin graves'},
  {cat:'thyroid', name:'Thyroglobulin', male:'<55', units:'ng/mL', note:'Tumor marker for differentiated thyroid cancer (papillary/follicular) follow-up after thyroidectomy ± RAI ablation. Detectable Tg post-thyroidectomy indicates residual or recurrent disease. Anti-Tg antibodies interfere with immunoassay — always measure simultaneously. Not useful for initial diagnosis of thyroid cancer.', aliases:'thyroglobulin tg tumor marker thyroid cancer surveillance'},

  // Endocrine
  {cat:'endocrine', name:'Prolactin', male:'2–18', female:'2–29', units:'ng/mL', note:'Hyperprolactinemia: rule out pregnancy first. Common causes: prolactinoma (most common pituitary adenoma), medications (antipsychotics, metoclopramide, domperidone, SSRIs), hypothyroidism, chest-wall stimulation. Mild elevation (<100) often medication-related; >200 ng/mL nearly diagnostic of prolactinoma. Macroprolactin (bound IgG) causes false elevation — request fractionation if asymptomatic.', aliases:'prolactin serum prl hyperprolactinemia'},
  {cat:'endocrine', name:'ACTH (morning)', male:'10–60', units:'pg/mL', note:'Collect 8 AM on ice; process immediately. High ACTH + high cortisol = Cushing disease (pituitary) or ectopic ACTH. Low ACTH + high cortisol = adrenal adenoma/carcinoma. Low ACTH + low cortisol = secondary/tertiary adrenal insufficiency. Pulsatile secretion limits single-value interpretation.', aliases:'acth adrenocorticotropic hormone adrenocorticotropin corticotropin'},
  {cat:'endocrine', name:'IGF-1', male:'See note (age-dependent)', units:'ng/mL', note:'Age-adjusted reference range required (declines with age after 30). Screening test for acromegaly (elevated) and adult GH deficiency (low). More stable than GH (not pulsatile). Random GH level unreliable — use IGF-1 as initial screen.', aliases:'igf-1 igf1 insulin-like growth factor somatomedin c acromegaly'},
  {cat:'endocrine', name:'Aldosterone', male:'7–30 (upright)', units:'ng/dL', note:'Position-dependent: collect upright (standing ≥30 min) for primary aldosteronism screening. Ratio: aldosterone (ng/dL) / renin (ng/mL/hr) >30 = screen positive for primary hyperaldosteronism (PA); confirm with salt-loading or fludrocortisone suppression test. Low in adrenal insufficiency, heparin use.', aliases:'aldosterone serum pa primary hyperaldosteronism conn'},
  {cat:'endocrine', name:'Renin (PRA)', male:'0.5–4.0 (upright)', units:'ng/mL/hr', note:'Plasma renin activity (PRA); some labs report direct renin (ng/L). Collect upright after 30-min ambulation, off diuretics/ACEi/ARBs ×2 weeks if possible. High renin + high aldosterone = secondary hyperaldosteronism (renovascular HTN, HF, cirrhosis). Low renin + high aldosterone = primary PA. Low renin + low aldosterone = 11β-hydroxylase deficiency, fludrocortisone.', aliases:'plasma renin activity pra direct renin'},
  {cat:'endocrine', name:'DHEA-S', male:'120–520', female:'45–380', units:'µg/dL', note:'Age-dependent (peaks 20–30, declines ~2%/year). Primarily adrenal androgen (vs. DHEA which is also gonadal). Elevated in adrenal hyperplasia (CAH), adrenocortical carcinoma, PCOS. Low in adrenal insufficiency. Not significantly affected by ACTH stimulation; stable marker.', aliases:'dhea-s dheas dehydroepiandrosterone sulfate adrenal androgen'},
  {cat:'endocrine', name:'Testosterone (total)', male:'300–1000', female:'15–70', units:'ng/dL', note:'AUA defines male hypogonadism <300 ng/dL; confirm with two AM measurements. Consider SHBG for calculated free testosterone in obesity or liver disease. Elevated in females: PCOS, adrenal/ovarian tumor, CAH. Testosterone >200 ng/dL in females warrants tumor workup.', aliases:'testosterone total serum hypogonadism'},
  {cat:'endocrine', name:'Free Testosterone', male:'55–215', female:'1.0–8.5', units:'pg/mL', note:'More clinically relevant in obesity (high SHBG lowers total T) and in women. Calculated free T (from total T + SHBG + albumin) is preferred over direct immunoassay (unreliable at low levels). Equilibrium dialysis is gold standard but rarely needed clinically.', aliases:'free testosterone calculated direct'},
  {cat:'endocrine', name:'SHBG', male:'10–57', female:'18–114', units:'nmol/L', note:'Sex hormone binding globulin. Elevated by estrogen (OCP, pregnancy), thyroid hormone, aging, liver disease. Decreased by androgens, insulin resistance, obesity, hypothyroidism. High SHBG → lower free testosterone even with normal total T. Order with testosterone when SHBG-altering conditions present.', aliases:'shbg sex hormone binding globulin testosterone binding'},
  {cat:'endocrine', name:'LH', male:'1.5–9.3', units:'mIU/mL', note:'Female: follicular 1.9–12.5; midcycle surge 8.7–76.3; luteal 0.5–16.9; postmenopausal 15.9–54.0 mIU/mL. High LH + low testosterone/estrogen = primary hypogonadism (testicular/ovarian failure). Low or inappropriately normal LH + low sex steroids = secondary (pituitary) or tertiary (hypothalamic) hypogonadism. LH surge triggers ovulation ~36h later.', aliases:'lh luteinizing hormone'},
  {cat:'endocrine', name:'FSH', male:'1.5–12.4', units:'mIU/mL', note:'Female: follicular 3.5–12.5; midcycle 4.7–21.5; luteal 1.7–7.7; postmenopausal 25.8–134.8 mIU/mL. Elevated FSH (>10 mIU/mL day 3) with low AMH suggests diminished ovarian reserve. Very high FSH in women aged <40 = premature ovarian insufficiency (POI). FSH >40 with amenorrhea >4 months confirms POI.', aliases:'fsh follicle stimulating hormone ovarian reserve'},
  {cat:'endocrine', name:'Estradiol (E2)', male:'10–40', units:'pg/mL', note:'Female (cycle-dependent): follicular 15–160; midcycle peak 100–500; luteal 40–200; postmenopausal <50 pg/mL. Elevated in males: gynecomastia, estrogen-secreting tumors, obesity (aromatization), liver disease. Low E2 + high FSH/LH = ovarian failure. Low E2 + low FSH/LH = hypothalamic/pituitary dysfunction.', aliases:'estradiol e2 estrogen female hormone'},
  {cat:'endocrine', name:'Progesterone', male:'<1', units:'ng/mL', note:'Female: follicular <1 ng/mL; luteal phase 2–25 ng/mL; confirms ovulation if >3 ng/mL (draw day 21 of 28-day cycle). First-trimester pregnancy: 11–44 ng/mL; <6 ng/mL suggests non-viable pregnancy or ectopic. Progesterone <3 in luteal phase = anovulation/luteal phase defect.', aliases:'progesterone serum luteal ovulation'},
  {cat:'endocrine', name:'PTH (intact)', male:'10–65', units:'pg/mL', note:'Draw simultaneously with serum calcium. High PTH + hypercalcemia = primary hyperparathyroidism (most often adenoma). High PTH + low/normal calcium = secondary HPT (CKD, vitamin D deficiency, malabsorption). Suppressed PTH + hypercalcemia = malignancy-related, granulomatous disease, vitamin D toxicity, milk-alkali.', aliases:'pth intact parathyroid hormone parathyroid'},
  {cat:'endocrine', name:'Ionized Calcium', male:'4.5–5.3', units:'mg/dL', note:'(= 1.12–1.32 mmol/L). Gold standard for calcium status — not affected by albumin, protein-binding, or pH (unlike total calcium). Essential in ICU, hypoalbuminemia, acid-base disorders. Correct for pH: acidosis increases ionized Ca; alkalosis decreases it. Symptoms of hypocalcemia: Chvostek/Trousseau signs, tetany, QT prolongation.', aliases:'ionized calcium ica free calcium ca2+'},
  {cat:'endocrine', name:'C-peptide (fasting)', male:'0.8–3.1', units:'ng/mL', note:'Co-secreted 1:1 with insulin; reflects endogenous insulin production. Low in T1DM (beta-cell failure), exogenous insulin injection (suppresses endogenous). Elevated in T2DM, insulinoma, sulfonylurea use. Useful to distinguish T1 vs T2DM, evaluate hypoglycemia etiology, and detect insulin factitia.', aliases:'c peptide c-peptide connecting peptide insulin'},
  {cat:'endocrine', name:'Insulin (fasting)', male:'2–20', units:'µIU/mL', note:'Fasting only — highly variable. Elevated in insulin resistance (T2DM, metabolic syndrome, PCOS), insulinoma, Cushing syndrome. HOMA-IR = [fasting insulin (µIU/mL) × fasting glucose (mg/dL)] / 405; >2.5 suggests insulin resistance. Fasting insulin alone is not diagnostic; use in context of glucose and HOMA-IR.', aliases:'insulin fasting serum homa-ir insulin resistance'},
  {cat:'endocrine', name:'AMH', male:'—', female:'1.0–3.5 (repro age)', units:'ng/mL', note:'Anti-Müllerian hormone. Cycle-independent marker of ovarian reserve — can be drawn any day. Elevated in PCOS (reflects increased antral follicle count). Low AMH: diminished ovarian reserve; very low (<0.2) = poor IVF response. Not validated for routine infertility prediction outside specialist context. Not clinically meaningful in males after puberty.', aliases:'amh anti mullerian hormone ovarian reserve pcos'},

  // Lipids
  {cat:'lipids', name:'Total Cholesterol', male:'<200 (desirable)', units:'mg/dL', note:'200–239 = borderline high; ≥240 = high. Interpret with LDL, HDL, and clinical ASCVD risk; total cholesterol alone is insufficient for treatment decisions.', aliases:'chol cholesterol total'},
  {cat:'lipids', name:'LDL Cholesterol', male:'<100 (optimal)', units:'mg/dL', note:'Targets by risk: <70 mg/dL for high ASCVD risk; <55 mg/dL for very high risk (recent ACS, multiple ASCVD events). Friedewald formula unreliable when TG >400 — use Martin-Hopkins or direct LDL.', aliases:'ldl low density lipoprotein ldl-c'},
  {cat:'lipids', name:'HDL Cholesterol', male:'>40', female:'>50', units:'mg/dL', note:'Protective factor. >60 mg/dL = negative ASCVD risk factor. <40 (M) or <50 (F) = low HDL risk factor. No approved drug therapy specifically targets low HDL.', aliases:'hdl high density lipoprotein hdl-c'},
  {cat:'lipids', name:'Triglycerides', male:'<150', units:'mg/dL', note:'150–199 = borderline; 200–499 = high; ≥500 = very high (acute pancreatitis risk). Fasting sample preferred. Elevated by alcohol, refined carbs, DM, hypothyroid, CKD.', aliases:'tg triglycerides trigs'},
  {cat:'lipids', name:'Non-HDL Cholesterol', male:'<130 (optimal)', units:'mg/dL', note:'Total Cholesterol − HDL. Better predictor than LDL in hypertriglyceridemia. Target = LDL goal + 30 mg/dL.', aliases:'non hdl cholesterol'},
  {cat:'lipids', name:'Lp(a)', male:'<30', units:'mg/dL', note:'Genetically determined ASCVD risk enhancer. Not routinely reduced by statins. Measure once in lifetime for risk stratification in intermediate ASCVD risk patients. Emerging Lp(a)-targeted therapies in clinical trials.', aliases:'lipoprotein a lpa'},
  {cat:'lipids', name:'ApoB', male:'<90 (high-risk: <80)', units:'mg/dL', note:'Reflects total atherogenic particle number (each VLDL, IDL, LDL, Lp(a) carries one ApoB). More accurate than LDL in metabolic syndrome, diabetes, and hypertriglyceridemia.', aliases:'apolipoprotein b apob'},
  {cat:'lipids', name:'ApoA-I', male:'>120', female:'>140', units:'mg/dL', note:'Major protein of HDL. Low ApoA-I independently correlates with ASCVD risk. May be more accurate than HDL-C in metabolic syndrome. Combined ApoB/ApoA-I ratio reflects the atherogenic-to-protective particle balance. Ratio >1.0 (M) or >0.9 (F) associated with significantly increased ASCVD risk.', aliases:'apolipoprotein a1 apoa1 hdl protein apob apoa ratio'},

  // Urinalysis
  {cat:'ua', name:'Specific Gravity', male:'1.005–1.030', units:'', note:'<1.003 = very dilute (DI, polydipsia). >1.030 = maximally concentrated (dehydration). Fixed SG 1.010 in CKD (isosthenuria).', aliases:'sg specific gravity urine'},
  {cat:'ua', name:'pH (urine)', male:'4.5–8.0', units:'', note:'Alkaline urine (>7): UTI with urease-producing organisms, type I RTA, vegetarian diet, bicarb supplementation. Acidic urine: gout, uric acid stones, type II RTA, high protein diet.', aliases:'urine ph'},
  {cat:'ua', name:'Protein (dipstick)', male:'Negative', units:'qualitative', note:'Trace–1+ may be benign (orthostatic, exercise). Persistent ≥1+ warrants quantification with urine protein:creatinine ratio or 24h collection.', aliases:'urine protein protein dipstick'},
  {cat:'ua', name:'Urine Protein:Cr Ratio', male:'<0.2', units:'mg/mg', note:'≈ 24h protein excretion in g/day. Nephrotic range >3.5 mg/mg. Nephritis range 0.5–3.5. Microalbuminuria range 30–300 mg/g (see albumin:Cr).', aliases:'upcr urine protein creatinine ratio'},
  {cat:'ua', name:'Urine Albumin:Cr Ratio', male:'<30', units:'mg/g', note:'Screening for diabetic nephropathy and CKD. 30–300 mg/g = moderately increased albuminuria (A2); >300 mg/g = severely increased (A3). Spot urine preferred over 24h.', aliases:'uacr microalbumin urine albumin creatinine ratio macr'},
  {cat:'ua', name:'Glucose (dipstick)', male:'Negative', units:'qualitative', note:'Glycosuria without hyperglycemia = renal glucosuria (Fanconi syndrome, SGLT2 inhibitors). Hyperglycemia >180 mg/dL exceeds renal threshold.', aliases:'urine glucose glucosuria'},
  {cat:'ua', name:'Ketones (urine)', male:'Negative', units:'qualitative', note:'DKA, fasting, starvation. Urine ketones may be negative in DKA with renal failure — check serum beta-hydroxybutyrate.', aliases:'urine ketones ketonuria'},
  {cat:'ua', name:'Blood (dipstick)', male:'Negative', units:'qualitative', note:'False positive with myoglobin (rhabdo), free hemoglobin (hemolysis). Confirmed hematuria: ≥3 RBCs/hpf on microscopy on 2 of 3 samples (AUA definition).', aliases:'urine blood hematuria dipstick'},
  {cat:'ua', name:'WBCs (microscopy)', male:'0–5', units:'/hpf', note:'≥10 WBCs/hpf = pyuria. Pyuria without bacteria: TB, STI, urethritis, interstitial nephritis, sterile pyuria. Culture if symptomatic.', aliases:'wbc urine microscopy pyuria'},
  {cat:'ua', name:'RBCs (microscopy)', male:'0–5', units:'/hpf', note:'Dysmorphic RBCs or RBC casts indicate glomerular origin (GN, vasculitis). Isomorphic RBCs suggest lower urinary tract source.', aliases:'rbc urine microscopy hematuria red cells'},
  {cat:'ua', name:'Nitrites', male:'Negative', units:'qualitative', note:'Positive = gram-negative bacteria (E. coli) reducing dietary nitrates. Gram-positive organisms do not reduce nitrates → nitrites negative in GPC UTI.', aliases:'urine nitrites nitrite dipstick'},
  {cat:'ua', name:'Leukocyte Esterase', male:'Negative', units:'qualitative', note:'Marker of pyuria/WBCs. False negatives: vitamin C, high SG, rifampin. Combines with nitrites for UTI screening (both negative has high NPV).', aliases:'le leukocyte esterase urine'},
  {cat:'ua', name:'Urine Osmolality', male:'50–1200', units:'mOsm/kg', note:'Distinguishes concentrated (>500) from dilute (<150) urine. In hyponatremia: Uosm >100 mOsm/kg suggests inappropriate ADH (SIADH, hypothyroid, adrenal insufficiency). In AKI: Uosm >500 = prerenal; <350 = intrinsic tubular injury. Maximal concentration ~1200 mOsm/kg reflects intact tubular function.', aliases:'urine osmolality uosm urine concentration'},
  {cat:'ua', name:'Urine Sodium (spot)', male:'Variable', units:'mEq/L', note:'Context-dependent; interpret with clinical status. Urine Na <20 mEq/L + hyponatremia = hypovolemia or edematous state (HF, cirrhosis). Urine Na >40 mEq/L + hyponatremia = SIADH, adrenal insufficiency, hypothyroidism. In AKI: UNa <20 = prerenal; >40 = intrinsic tubular injury (ATN).', aliases:'urine sodium una spot urine'},
  {cat:'ua', name:'Urine Creatinine (spot)', male:'20–300', units:'mg/dL', note:'Used as denominator for spot urine ratios (protein:Cr, albumin:Cr). Wide normal range. Very low (<20 mg/dL) may indicate a dilute or improperly collected sample, reducing ratio validity.', aliases:'urine creatinine spot ucr'},
  {cat:'ua', name:'FENa', male:'<1%', units:'%', note:'Fractional excretion of sodium = (uNa × sCr) / (sNa × uCr) × 100. <1% = prerenal AKI (intact tubular Na reabsorption); >2% = intrinsic AKI (ATN). Unreliable with diuretics — use FEUrea instead. Also unreliable in contrast nephropathy, myoglobinuria, early obstruction.', aliases:'fena fractional excretion sodium aki renal failure prerenal'},
  {cat:'ua', name:'FEUrea', male:'<35%', units:'%', note:'Fractional excretion of urea = (uUrea × sCr) / (sUrea × uCr) × 100. Preferred over FENa in patients on diuretics (diuretics increase FENa but do not affect urea reabsorption). <35% = prerenal; >50% = intrinsic AKI (ATN). More reliable than FENa in diuretic-treated patients.', aliases:'feurea fractional excretion urea diuretics aki prerenal'},

  // ABG
  {cat:'abg', name:'Arterial pH', male:'7.35–7.45', units:'', note:'Acidosis <7.35: respiratory (↑PCO2) or metabolic (↓HCO3). Alkalosis >7.45: respiratory (↓PCO2) or metabolic (↑HCO3). Compensatory responses never fully correct pH.', aliases:'ph arterial blood gas abg'},
  {cat:'abg', name:'PaO₂', male:'75–100', units:'mmHg', note:'Age-adjusted: ≈ 103 − (0.42 × age). Hypoxemia <60 mmHg. Obtain with FiO2 to calculate P/F ratio (ARDS: <300). SpO2 unreliable in severe anemia or carboxyhemoglobin.', aliases:'pao2 partial pressure oxygen arterial'},
  {cat:'abg', name:'PaCO₂', male:'35–45', units:'mmHg', note:'Hypoventilation >45 (respiratory acidosis). Hyperventilation <35 (respiratory alkalosis or metabolic compensation). Winter formula: expected PCO2 in met acidosis = 1.5(HCO3) + 8 ± 2.', aliases:'paco2 partial pressure co2 carbon dioxide'},
  {cat:'abg', name:'HCO₃ (calculated)', male:'22–26', units:'mEq/L', note:'Calculated from pH and PCO2 (Henderson-Hasselbalch). Compare to serum CO2 — discrepancy suggests lab error or mixed disorder.', aliases:'bicarbonate hco3 abg calculated'},
  {cat:'abg', name:'Base Excess / Deficit', male:'-2 to +2', units:'mEq/L', note:'Base excess > +2 = metabolic alkalosis. Base deficit (negative BE) < −2 = metabolic acidosis. Useful in trauma resuscitation (BD > −6 suggests significant shock).', aliases:'base excess deficit be bd'},
  {cat:'abg', name:'SaO₂', male:'≥95', units:'%', note:'SpO2 correlates well with SaO2 >80%. Target SpO2 94–98% for most patients; 88–92% in COPD/hypercapnic patients to avoid hypercapnia worsening.', aliases:'sao2 spo2 oxygen saturation'},
  {cat:'abg', name:'A-a Gradient', male:'<(age/4) + 4', units:'mmHg', note:'A-a = [FiO2 × (Patm − 47) − PaCO2/0.8] − PaO2. Room air: A-a = [0.21×713 − PCO2/0.8] − PaO2. Elevated: V/Q mismatch, shunt, diffusion impairment. Normal for age: (age + 10)/4.', aliases:'aa gradient alveolar arterial oxygen difference'},
  {cat:'abg', name:'Carboxyhemoglobin (COHb)', male:'<3% (non-smoker)\n<10% (smoker)', units:'%', note:'Detectable only by co-oximetry — pulse oximetry is falsely normal (SpO2 reads ~100%). CO poisoning: mild 15–25% (headache, nausea); moderate 25–40% (confusion, syncope); severe >40% (coma, death). Treat with 100% O2 (half-life 5h room air → 60–90 min on 100% O2); consider hyperbaric O2 for >25%, pregnancy, cardiac involvement, or neurologic symptoms.', aliases:'cohb carboxyhemoglobin carbon monoxide co poisoning'},
  {cat:'abg', name:'Methemoglobin (MetHb)', male:'<1%', units:'%', note:'Fe³⁺ hemoglobin cannot carry O2. Causes: dapsone, nitrates, benzocaine, primaquine, nitroprusside. Clinical cyanosis at >15%; blood appears chocolate-brown. Pulse oximetry reads falsely ~85% — diagnose by co-oximetry. Treat with methylene blue 1–2 mg/kg IV if symptomatic or MetHb >20%; avoid in G6PD deficiency (hemolysis risk).', aliases:'methemoglobin methb methemoglobinemia'},

  // Miscellaneous
  {cat:'misc', name:'HbA1c', male:'<5.7%', units:'%', note:'5.7–6.4% = prediabetes; ≥6.5% = diabetes. Treatment targets: <7% most adults, <8% frail/limited life expectancy. Mean glucose (mg/dL) ≈ (HbA1c × 28.7) − 46.7. Unreliable in hemolysis, hemoglobinopathy, iron deficiency.', aliases:'hemoglobin a1c glycated hemoglobin hba1c a1c glycohemoglobin'},
  {cat:'misc', name:'Ferritin', male:'12–300', female:'12–150', units:'ng/mL', note:'Iron deficiency: <12 ng/mL (nearly diagnostic). Chronic disease: normal/elevated despite iron deficiency. Acute phase reactant — ferritin >300 (M) or >200 (F) may mask deficiency in inflammation. Hemochromatosis screening: >200 (F), >300 (M) + high transferrin sat.', aliases:'ferritin serum iron stores'},
  {cat:'misc', name:'Serum Iron', male:'60–170', units:'µg/dL', note:'Diurnal variation (higher AM). Elevated in hemochromatosis, hemolysis, iron toxicity. Low in iron deficiency, AOCD, pregnancy.', aliases:'serum iron fe'},
  {cat:'misc', name:'TIBC', male:'250–370', units:'µg/dL', note:'Total iron binding capacity — inversely related to serum ferritin. Elevated in iron deficiency. Low in chronic disease/AOCD, malnutrition.', aliases:'tibc total iron binding capacity'},
  {cat:'misc', name:'Transferrin Saturation', male:'15–50', units:'%', note:'Iron sat = serum iron / TIBC × 100. <15% = iron deficiency or AOCD. >45% = iron overload / hemochromatosis screening threshold (confirm with ferritin and genetic testing).', aliases:'transferrin saturation tsat iron saturation'},
  {cat:'misc', name:'Vitamin B12', male:'200–900', units:'pg/mL', note:'Deficiency <200 pg/mL. Borderline 200–300: confirm with methylmalonic acid and homocysteine (both elevated in true deficiency). Common causes: veganism, pernicious anemia, metformin use.', aliases:'b12 cobalamin vitamin b12 cyanocobalamin'},
  {cat:'misc', name:'Folate (serum)', male:'>3.0', units:'ng/mL', note:'Serum folate reflects recent intake (last several days). RBC folate better reflects long-term status. Low in malabsorption, alcoholism, medications (methotrexate, phenytoin, sulfasalazine).', aliases:'folic acid folate serum rbc'},
  {cat:'misc', name:'Vitamin D (25-OH)', male:'30–80', units:'ng/mL', note:'Deficiency <20 ng/mL; insufficiency 20–29 ng/mL; optimal 30–60 ng/mL; toxicity >100 ng/mL. 25-OH-D is the storage form — best test for deficiency. Convert: ng/mL × 2.496 = nmol/L.', aliases:'vitamin d 25 oh calcidiol 25 hydroxyvitamin cholecalciferol'},
  {cat:'misc', name:'Uric Acid', male:'3.5–7.2', female:'2.6–6.0', units:'mg/dL', note:'Gout: serum urate ≥6.8 mg/dL (saturation threshold). Target <6.0 mg/dL for gout management (ULT). Asymptomatic hyperuricemia does not generally require treatment.', aliases:'uric acid serum urate gout'},
  {cat:'misc', name:'ESR', male:'0–15 (<50yr)\n0–20 (≥50yr)', female:'0–20 (<50yr)\n0–30 (≥50yr)', units:'mm/hr', note:'Nonspecific inflammatory marker. Useful for screening/monitoring temporal arteritis (ESR >50 suggestive, >100 strongly associated), polymyalgia rheumatica. Elevated in infection, autoimmune, malignancy, pregnancy.', aliases:'esr erythrocyte sedimentation rate sed rate'},
  {cat:'misc', name:'CRP', male:'<1.0', units:'mg/L', note:'Rises rapidly in inflammation (within hours). hs-CRP for cardiovascular risk: <1.0 mg/L = low; 1–3 = moderate; >3 = high. Very high CRP (>100 mg/L) suggests serious bacterial infection or flare.', aliases:'crp c reactive protein hs-crp high sensitivity'},
  {cat:'misc', name:'Procalcitonin', male:'<0.25', units:'ng/mL', note:'<0.1 = bacterial infection very unlikely. 0.25–0.5 = possible; >0.5 = bacterial infection likely; >2 = severe bacterial infection/sepsis likely. Guides antibiotic initiation and de-escalation. Unreliable in fungal infections, certain viral infections.', aliases:'procalcitonin pct'},
  {cat:'misc', name:'Lactate', male:'0.5–2.0', units:'mmol/L', note:'Sepsis concern: ≥2 mmol/L (resuscitate, reassess). Septic shock: ≥4 mmol/L (high mortality). Clearance goal ≥10% per 2h. Also elevated: hepatic failure, ischemia, metformin toxicity (type B), severe anemia.', aliases:'lactate lactic acid'},
  {cat:'misc', name:'Ammonia', male:'15–45', units:'µg/dL', note:'Elevated in hepatic encephalopathy (liver failure, portosystemic shunt). Also elevated in urea cycle disorders, GI bleeding, UTI with urease organisms. Tourniquet/delay in processing falsely elevates.', aliases:'ammonia serum nh3'},
  {cat:'misc', name:'Cortisol (AM)', male:'10–20 (drawn 8 AM)', units:'µg/dL', note:'For adrenal insufficiency screening: AM cortisol >18 µg/dL generally rules out primary AI. <3 µg/dL diagnostic of AI. 3–18 µg/dL: cosyntropin stimulation test (target >18 µg/dL at 30–60 min).', aliases:'cortisol am serum morning hydrocortisone'},
  {cat:'misc', name:'PSA (Total)', male:'<4.0 (general)\nAge-specific: see note', female:'—', units:'ng/mL', note:'Age-specific: <2.5 (age 40–49), <3.5 (50–59), <4.5 (60–69), <6.5 (70+). PSA velocity >0.75 ng/mL/yr or PSA density >0.15 ng/mL/cc raises concern. BPH, prostatitis, and vigorous activity can elevate PSA. Discuss risks/benefits before screening.', aliases:'psa prostate specific antigen'},
  {cat:'misc', name:'hCG (serum)', male:'<5', units:'mIU/mL', note:'In pregnancy: doubles every 48h in early viable IUP. Plateau or decline may indicate miscarriage or ectopic. Discriminatory zone ~1,500–3,500 mIU/mL (IUP should be visible on transvaginal US above this level).', aliases:'hcg human chorionic gonadotropin beta hcg pregnancy'},
  {cat:'misc', name:'Homocysteine', male:'<15', units:'µmol/L', note:'Elevated in B12, folate, or B6 deficiency (most common cause). Also in renal failure, hypothyroidism, MTHFR polymorphism, medications (MTX, phenytoin, nicotinic acid). Both MMA and homocysteine elevated = B12 deficiency. Only homocysteine elevated = folate or B6 deficiency. Independent ASCVD risk enhancer.', aliases:'homocysteine serum hcy b12 folate deficiency cardiovascular'},
  {cat:'misc', name:'Methylmalonic Acid (MMA)', male:'<0.40', units:'µmol/L', note:'Most sensitive test for functional B12 deficiency — elevated even when serum B12 is borderline (200–300 pg/mL). Also elevated in CKD (renally excreted) — check creatinine before interpreting. Normal MMA + normal homocysteine reliably rules out functional B12 deficiency.', aliases:'methylmalonic acid mma b12 deficiency functional'},
  {cat:'misc', name:'Alpha-1 Antitrypsin', male:'100–200', units:'mg/dL', note:'Protease inhibitor produced by liver. Low levels in A1AT deficiency (Pi*ZZ genotype most severe) — causes panacinar emphysema (young non-smokers, basilar distribution) and liver disease (cholestasis, cirrhosis). Screen with serum level; confirm with phenotyping (PI typing). Normal: 100–200 mg/dL; severe deficiency: <50 mg/dL.', aliases:'alpha-1 antitrypsin a1at a1-antitrypsin emphysema copd'},
  {cat:'misc', name:'Copper (serum)', male:'70–140', units:'µg/dL', note:'Elevated in Wilson disease (free copper elevated despite low ceruloplasmin-bound copper), cholestasis, pregnancy. Low in nutritional copper deficiency (rare — malabsorption, TPN without supplementation). 24h urine copper >100 µg/day used for Wilson disease diagnosis and monitoring treatment.', aliases:'copper serum cu wilson disease'},
  {cat:'misc', name:'Zinc (serum)', male:'60–120', units:'µg/dL', note:'Zinc deficiency causes dermatitis (acral/perioral), alopecia, hypogeusia, impaired wound healing, immune dysfunction, male hypogonadism. Risk groups: IBD, malabsorption, chronic diarrhea, alcoholism, poor diet, TPN. Hemolysis falsely elevates serum zinc.', aliases:'zinc serum zn deficiency'},
  {cat:'misc', name:'Lead (blood)', male:'<5', units:'µg/dL', note:'CDC reference value <5 µg/dL (no safe level established in children). Chelation considered at >45 µg/dL in adults. Sources: old paint, contaminated water (lead pipes), occupational exposure. Symptoms at >10 µg/dL: fatigue, cognitive impairment, abdominal pain. High levels: peripheral neuropathy, encephalopathy, basophilic stippling on CBC.', aliases:'blood lead level bll lead poisoning plumbism'},
  {cat:'misc', name:'Thiamine (B1)', male:'70–180', units:'nmol/L', note:'Deficiency causes Wernicke encephalopathy (confusion, ataxia, ophthalmoplegia — triad present in <33% of cases), Korsakoff syndrome, and beriberi (wet: high-output HF; dry: polyneuropathy). At-risk: alcoholism, malnutrition, hyperemesis, bariatric surgery, prolonged TPN. Give empiric IV thiamine before glucose administration in any altered mental status of unknown cause.', aliases:'thiamine b1 vitamin b1 wernicke beriberi korsakoff'},

  // Immunology
  {cat:'immune', name:'ANA', male:'Negative (<1:40)', units:'titer', note:'Positive ANA (≥1:80) in SLE (>95%), scleroderma, Sjögren, MCTD, drug-induced. Low-titer positives (1:40–1:80) common in healthy adults (~30%). Pattern guides further testing: homogenous (anti-dsDNA), speckled (anti-Sm, anti-SSA/B).', aliases:'ana antinuclear antibody'},
  {cat:'immune', name:'Anti-dsDNA', male:'<5', units:'IU/mL', note:'Highly specific for SLE (>99%); sensitivity 70%. Correlates with disease activity; useful for monitoring. Order when ANA positive with homogenous pattern.', aliases:'anti dsdna double stranded dna antibody sle'},
  {cat:'immune', name:'Anti-Smith (Anti-Sm)', male:'Negative', units:'qualitative', note:'Highly specific for SLE (>99% specificity) but only 25–30% sensitive. Not useful for monitoring activity.', aliases:'anti smith sm antibody sle'},
  {cat:'immune', name:'Anti-SSA (Ro)', male:'Negative', units:'qualitative', note:'Elevated in Sjögren syndrome (75%), SLE (30–40%). Associated with neonatal lupus and congenital heart block. Check in pregnancy with known autoimmune disease.', aliases:'anti ssa ro antibody sjogren'},
  {cat:'immune', name:'Anti-SSB (La)', male:'Negative', units:'qualitative', note:'Often positive with anti-SSA. Sjögren syndrome (50%), SLE (15%). Anti-SSB positivity without anti-SSA unusual.', aliases:'anti ssb la antibody sjogren'},
  {cat:'immune', name:'Complement C3', male:'90–180', units:'mg/dL', note:'Low in active SLE, type II MPGN, cryoglobulinemia, hepatic failure, SBP. C3 consumption in active immune complex disease. Acute phase reactant — may be normal despite consumption in acute lupus flare.', aliases:'complement c3 c3'},
  {cat:'immune', name:'Complement C4', male:'16–47', units:'mg/dL', note:'Low in lupus, hereditary angioedema (HAE), C4 null gene (common — 1–3% of population has one null allele, causing persistently low C4 without disease). Very low C4 + normal C3 = HAE or C4 null.', aliases:'complement c4 c4'},
  {cat:'immune', name:'Rheumatoid Factor (RF)', male:'<15–20', units:'IU/mL', note:'RA: 60–70% sensitivity. Also positive in Sjögren, SLE, cryoglobulinemia, hepatitis C, SBE, older adults. Low specificity — use with anti-CCP for RA diagnosis.', aliases:'rf rheumatoid factor'},
  {cat:'immune', name:'Anti-CCP', male:'<20', units:'U/mL', note:'Specificity >95% for RA; sensitivity 70%. Can be positive before symptoms. Combined with RF: high PPV for RA. Negative RF + positive anti-CCP: consider seronegative RA.', aliases:'anti ccp cyclic citrullinated peptide antibody ra'},
  {cat:'immune', name:'c-ANCA / PR3-ANCA', male:'Negative', units:'titer', note:'Cytoplasmic ANCA targeting PR3. Associated with GPA (Granulomatosis with Polyangiitis / Wegener). Sensitivity ~90% for active GPA. Use both ANCA pattern and ELISA (PR3 + MPO) for evaluation.', aliases:'canca pr3 anca wegener gpa'},
  {cat:'immune', name:'p-ANCA / MPO-ANCA', male:'Negative', units:'titer', note:'Perinuclear ANCA targeting MPO. Associated with microscopic polyangiitis, eosinophilic GPA (Churg-Strauss), anti-GBM disease. Also elevated in IBD, PSC (low titer).', aliases:'panca mpo anca microscopic polyangiitis mpa'},
  {cat:'immune', name:'Antiphospholipid Abs', male:'Negative', units:'titer/U', note:'Panel: anticardiolipin (aCL) IgG/IgM, anti-β2-glycoprotein I IgG/IgM, lupus anticoagulant (LA). APS requires ≥1 clinical criterion (thrombosis or pregnancy morbidity) + ≥1 lab criterion positive on ≥2 occasions ≥12 weeks apart. Triple positivity (all 3 tests) carries highest thrombotic risk. LA prolongs aPTT but paradoxically increases clotting.', aliases:'antiphospholipid antibody aps lupus anticoagulant anticardiolipin anti-beta2-gp1 aps'},
  {cat:'immune', name:'Anti-Histone Ab', male:'Negative', units:'qualitative', note:'Positive in >95% of drug-induced lupus (DIL). Causes: hydralazine, procainamide, isoniazid, methyldopa, minocycline, TNF inhibitors. Anti-dsDNA typically negative in DIL (unlike idiopathic SLE). Symptoms resolve with drug discontinuation. Positive ANA + positive anti-histone without dsDNA = suspect DIL.', aliases:'anti histone antibody drug induced lupus dil'},
  {cat:'immune', name:'Cryoglobulins', male:'Negative', units:'qualitative', note:'Type I (monoclonal — myeloma, Waldenström): hyperviscosity syndrome. Type II (mixed, HCV most common): vasculitis, palpable purpura, peripheral neuropathy, membranoproliferative GN. Type III (polyclonal — chronic infection, autoimmune). Must collect and transport at 37°C — cold precipitation invalidates result if cooled before processing.', aliases:'cryoglobulins cryoglobulinemia type 1 2 3 hcv'},
  {cat:'immune', name:'IgG / IgA / IgM', male:'IgG: 700–1600\nIgA: 70–400\nIgM: 40–230', units:'mg/dL', note:'Hypogammaglobulinemia (<500 IgG): common variable immunodeficiency (CVID), agammaglobulinemia, lymphoma, CLL, post-rituximab. Hypergammaglobulinemia: monoclonal (order SPEP/SFLC) vs polyclonal (chronic infection, autoimmune, cirrhosis). IgA deficiency (most common primary immunodeficiency): risk for CVID, anaphylaxis to blood products.', aliases:'immunoglobulin igg iga igm serum quantitative levels cvid'},

  // Tumor Markers
  {cat:'tumor', name:'CEA', male:'<3.0 (non-smoker)\n<5.0 (smoker)', units:'ng/mL', note:'Monitoring colorectal cancer recurrence — draw baseline before surgery, then q3–6 months for 5 years. Not used for screening (low sensitivity/specificity). Also elevated in lung, breast, gastric, pancreatic cancer, and benign conditions (smoking, IBD, liver disease). Rising CEA post-resection suggests recurrence — confirm with imaging.', aliases:'cea carcinoembryonic antigen colorectal cancer crc'},
  {cat:'tumor', name:'CA 19-9', male:'<37', units:'U/mL', note:'Pancreatic cancer: sensitivity ~79%, specificity ~82% for unresectable disease. Not for screening. Monitor response and recurrence post-resection. Also elevated in biliary cancer, gastric cancer, pancreatitis, cholangitis, cholestasis. Lewis antigen-negative individuals (~5% of population) cannot produce CA 19-9 — always negative regardless of disease.', aliases:'ca19-9 ca 19-9 pancreatic cancer biliary cholangiocarcinoma'},
  {cat:'tumor', name:'CA-125', male:'<35', units:'U/mL', note:'Ovarian cancer monitoring — not screening. Elevated in 80% of epithelial ovarian cancers; less sensitive for early-stage. Also elevated in endometriosis, PID, pregnancy, pleural/pericardial effusion, liver disease. ROMA score (CA-125 + HE4 + menopausal status) improves ovarian cancer risk stratification.', aliases:'ca 125 ca125 ovarian cancer epithelial'},
  {cat:'tumor', name:'CA 15-3 / CA 27.29', male:'<30 / <38', units:'U/mL', note:'Breast cancer markers for monitoring metastatic disease and treatment response — not for screening or diagnosis. CA 27.29 is more sensitive. Rising values during treatment suggest progression; declining values suggest response. Also elevated in liver, lung, ovarian cancer, and benign breast/liver conditions.', aliases:'ca 15-3 ca15-3 ca 27.29 ca27.29 breast cancer monitoring'},
  {cat:'tumor', name:'AFP (Alpha-Fetoprotein)', male:'<10', units:'ng/mL', note:'HCC surveillance: used with liver ultrasound q6 months in cirrhosis patients. AFP >200 ng/mL with compatible imaging can diagnose HCC without biopsy. Also elevated in nonseminomatous germ cell tumors (NSGCT) — used for staging and post-orchiectomy monitoring. Elevated in pregnancy, hepatitis, liver regeneration. Normal in ~30–40% of early HCC.', aliases:'afp alpha fetoprotein hepatocellular carcinoma hcc germ cell testicular nsgct'},
  {cat:'tumor', name:'PSA Free:Total Ratio', male:'>25% lower risk', units:'%', note:'Order when total PSA is 4–10 ng/mL (gray zone). Free PSA <10%: ~56% prostate cancer risk. Free PSA >25%: ~8% risk. Prostate cancer preferentially binds PSA — lowers the free fraction. BPH and normal tissue release more free PSA. Improves specificity without reducing sensitivity compared to total PSA alone.', aliases:'free psa free to total psa ratio prostate cancer'},
  {cat:'tumor', name:'Beta-hCG (Tumor)', male:'<5', units:'mIU/mL', note:'Tumor marker for gestational trophoblastic disease (molar pregnancy, choriocarcinoma) and nonseminomatous germ cell tumors (NSGCT). Complete hydatidiform mole: typically >100,000 mIU/mL. Used for diagnosis, staging, treatment monitoring, and surveillance. Low-level elevation (<50 mIU/mL) may represent phantom hCG (heterophile antibodies) — confirm with serial measurements.', aliases:'beta hcg bhcg tumor marker germ cell trophoblastic choriocarcinoma molar'},

  // Drug Levels
  {cat:'drug', name:'Vancomycin (AUC₀₋₂₄)', male:'400–600', units:'mg·h/L', note:'ASHP/SIDP/IDSA 2020 guidelines recommend AUC-guided monitoring over trough-only for serious MRSA infections. Target AUC₀₋₂₄ 400–600 mg·h/L (correlates with efficacy and minimizes nephrotoxicity). Bayesian software with 2 levels preferred. AUC-guided dosing reduces nephrotoxicity vs. high-trough approaches.', aliases:'vancomycin auc area under curve mrsa monitoring pk'},
  {cat:'drug', name:'Vancomycin (trough)', male:'15–20', units:'mg/L', note:'Traditional trough-only monitoring (second-line per 2020 guidelines; AUC preferred). Target trough 15–20 mg/L for serious MRSA; 10–15 mg/L for less severe infections. Collect 30 min before next dose at steady state (after 4th dose for q12h or 5th for q8h). Trough >20 mg/L associated with nephrotoxicity.', aliases:'vancomycin trough level monitoring mrsa'},
  {cat:'drug', name:'Aminoglycosides (Gent/Tobra)', male:'Peak: 5–10\nTrough: <2', units:'µg/mL', note:'Traditional dosing: peak 5–10 µg/mL (draw 30 min after infusion end); trough <2 µg/mL (30 min before next dose). Extended-interval once-daily dosing: check level at 6–14h and use Hartford nomogram. Trough >2 µg/mL → hold dose. Monitor renal function and audiometry for ototoxicity (irreversible). Amikacin peaks 20–30, troughs <10 µg/mL.', aliases:'gentamicin tobramycin aminoglycoside level peak trough amikacin'},
  {cat:'drug', name:'Digoxin', male:'0.5–2.0', units:'ng/mL', note:'Draw ≥6h after last dose (distribution phase). HF target: 0.5–0.9 ng/mL (higher levels associated with increased mortality in HF-rEF). AFib rate control: 0.8–2.0 ng/mL. Toxicity risk >2.0 ng/mL, especially with hypokalemia, hypomagnesemia, or hypothyroidism. Classic toxicity: yellow-green halos (xanthopsia), nausea, bradyarrhythmias, AV block.', aliases:'digoxin level digitalis toxicity monitoring lanoxin'},
  {cat:'drug', name:'Phenytoin (total)', male:'10–20', units:'µg/mL', note:'Correct for hypoalbuminemia: adjusted phenytoin = measured / (0.1 × albumin + 0.1). Zero-order kinetics at therapeutic levels — small dose increases cause disproportionately large level increases. Draw trough for monitoring. Fosphenytoin levels reported as phenytoin equivalents (PE).', aliases:'phenytoin dilantin level anticonvulsant epilepsy albumin correction'},
  {cat:'drug', name:'Phenytoin (free)', male:'1–2', units:'µg/mL', note:'Free (unbound) phenytoin preferred in hypoalbuminemia (<3.0 g/dL), renal failure, pregnancy, and critical illness where protein binding is altered. Free fraction normally 10% of total. Free >2 µg/mL = toxic range even if total is normal. Order when total level is inconsistent with clinical presentation.', aliases:'free phenytoin unbound phenytoin level critical illness'},
  {cat:'drug', name:'Lithium', male:'0.6–1.2 (maintenance)', units:'mEq/L', note:'Draw 12h post-dose trough. Acute mania target: 0.8–1.2 mEq/L; maintenance: 0.6–1.0 mEq/L. Toxicity >1.5 mEq/L: coarse tremor, ataxia, confusion. Severe toxicity >2.0 mEq/L: seizures, coma, cardiac arrhythmias. NSAIDs, thiazides, and ACEi significantly increase lithium levels — counsel patients.', aliases:'lithium level bipolar monitoring toxicity'},
  {cat:'drug', name:'Valproic Acid', male:'50–100', units:'µg/mL', note:'Seizure target: 50–100 µg/mL; some protocols up to 125 µg/mL. Draw trough. Monitor LFTs and ammonia — valproate-induced hyperammonemic encephalopathy can occur with normal LFTs. Teratogenic (neural tube defects) — avoid in pregnancy or ensure high-dose folate. Also causes pancreatitis, thrombocytopenia, weight gain.', aliases:'valproic acid valproate depakote divalproex level epilepsy'},
  {cat:'drug', name:'Carbamazepine', male:'4–12', units:'µg/mL', note:'Draw trough. Potent CYP3A4/1A2 inducer — autoinduces own metabolism (levels may fall 3–4 weeks after initiation requiring dose increase). Active metabolite (CBZ-10,11-epoxide) contributes to efficacy and toxicity. Toxicity: diplopia, ataxia, nausea. Rare: aplastic anemia, SIADH, Stevens-Johnson syndrome (HLA-B*1502 in Asian patients).', aliases:'carbamazepine tegretol level anticonvulsant epilepsy'},
  {cat:'drug', name:'Tacrolimus', male:'5–15 (protocol-dependent)', units:'ng/mL', note:'Targets are organ- and time-specific — always confirm with local protocol. Kidney transplant: early 10–15, maintenance 5–10 ng/mL. Liver: 5–15 ng/mL. Heart: 10–15 ng/mL. Draw whole blood trough (12–24h after last dose). Nephrotoxic; dose-reduce if creatinine rising with therapeutic levels. Major CYP3A4 substrate — many drug interactions.', aliases:'tacrolimus fk506 prograf trough level transplant immunosuppression'},
  {cat:'drug', name:'Cyclosporine', male:'100–300 (protocol-dependent)', units:'ng/mL', note:'Target is organ- and time-specific — confirm with local protocol. Kidney early: 150–300; maintenance: 75–150 ng/mL. Draw whole blood trough (C0) before AM dose. C2 monitoring (2h post-dose, target ~1000 ng/mL) used at some centers for absorption assessment. Nephrotoxic, neurotoxic. CYP3A4 substrate — extensive drug interactions.', aliases:'cyclosporine cyclosporin neoral sandimmune level transplant monitoring'},
  {cat:'drug', name:'Methotrexate (high-dose)', male:'<150 µmol/L at 24h\n<0.4 µmol/L at 72h', units:'µmol/L', note:'High-dose MTX monitoring: 24h level <150 µmol/L; 48h <3 µmol/L; 72h <0.4 µmol/L (leucovorin rescue endpoint — continue until <0.1 µmol/L). Delayed clearance risks: effusions/ascites (third-space), renal impairment, drug interactions (NSAIDs, PPIs, penicillins, trimethoprim). Not used for low-dose MTX (RA, psoriasis — no monitoring required).', aliases:'methotrexate level mtx monitoring high dose leucovorin rescue oncology'},

];

// ── App state ──────────────────────────────────────────────────────────────────
let activeCat = 'all';
let searchQuery = '';

function buildCatFilters() {
  const wrap = document.getElementById('catFilters');
  const allBtn = document.createElement('button');
  allBtn.className = 'tab-btn active';
  allBtn.textContent = 'All';
  allBtn.dataset.cat = 'all';
  wrap.appendChild(allBtn);
  for (const c of CATS) {
    const btn = document.createElement('button');
    btn.className = 'tab-btn';
    btn.textContent = c.label;
    btn.dataset.cat = c.id;
    wrap.appendChild(btn);
  }
  wrap.addEventListener('click', e => {
    const btn = e.target.closest('.tab-btn');
    if (!btn) return;
    wrap.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    activeCat = btn.dataset.cat;
    render();
  });
}

function matches(lab) {
  if (activeCat !== 'all' && lab.cat !== activeCat) return false;
  if (!searchQuery) return true;
  const q = searchQuery;
  return lab.name.toLowerCase().includes(q) ||
    (lab.aliases || '').toLowerCase().includes(q) ||
    (lab.units || '').toLowerCase().includes(q);
}

function render() {
  const content = document.getElementById('labContent');
  const catsToShow = activeCat === 'all' ? CATS : CATS.filter(c => c.id === activeCat);
  let html = '';
  let totalCount = 0;

  for (const cat of catsToShow) {
    const items = LABS.filter(l => l.cat === cat.id && matches(l));
    if (!items.length) continue;
    totalCount += items.length;

    const rows = items.map(l => {
      const hasSexDiff = l.female !== undefined && l.female !== l.male;
      const rangeHtml = hasSexDiff
        ? `<div class="td-range">${esc(l.male)}</div><div class="td-range-f">F: ${esc(l.female)}</div>`
        : `<div class="td-range">${esc(l.male)}</div>`;
      return `<tr>
        <td class="td-name">${esc(l.name)}</td>
        <td>${rangeHtml}</td>
        <td class="td-units">${esc(l.units)}</td>
        <td class="td-note">${esc(l.note)}</td>
      </tr>`;
    }).join('');

    html += `<div class="lab-section">
      <div class="lab-section-title">${esc(cat.label)}</div>
      <table class="lab-table">
        <tr>
          <th>Test</th>
          <th>Reference Range</th>
          <th>Units</th>
          <th>Clinical Notes</th>
        </tr>
        ${rows}
      </table>
    </div>`;
  }

  if (!totalCount) {
    html = `<div class="no-results">No results for "${esc(searchQuery)}"</div>`;
  }

  content.innerHTML = html;
}

document.getElementById('labSearch').addEventListener('input', e => {
  searchQuery = e.target.value.trim().toLowerCase();
  render();
});

buildCatFilters();
render();
